// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whtufjhhsppmqlbojejb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndodHVmamhoc3BwbXFsYm9qZWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTkwMzUsImV4cCI6MjA2NjU3NTAzNX0.LbAe4GaTuMjmUnYbPxcAqmwVt4iRICKXn1YwCC1bacE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);